### ISSUE TITLE
Use new MAINTAINERS and CONTRIBUTING format

### ISSUE THREAD

**Issue by stevemar** [IBM/image-analysis-iot-alert#2]
See https://github.com/IBM/Predictive-Market-Stress-Testing/blob/master/MAINTAINERS.md and https://github.com/IBM/Predictive-Market-Stress-Testing/blob/master/CONTRIBUTING.md for examples you can copy and paste

**Comment by hovig** [comment]
Thanks Steve. I update these 2 markdown files.
